# Site settings
title: Flatiron Coding Journey
header-img: img/home-bg.png
email: blinded93@gmail.com
copyright_name: blinded93
description: > # this means to ignore newlines until "baseurl:"
  Changing my life one keystroke at a time..
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username: blinded93
learn_profile: blinded93
email_username: blinded93@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
