# Site settings
title: Flatiron Coding Journey
logo: img/lone-milky-way1.jpg
email: blinded93@gmail.com
copyright_name: blinded93
description: > # this means to ignore newlines until "baseurl:"
  Changing my life one keystroke at a time..
<<<<<<< HEAD
baseurl: ""
=======
baseurl: "" # the subpath of your site, e.g. /blog
>>>>>>> 67d2078be246a4ea1408e16fd34074bc240f2b16
twitter_username:
github_username: blinded93
learn_profile: blinded93
email_username: blinded93@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
theme: "jekyll-theme-minimal"
plugins: [jekyll-paginate, jekyll-feed]
